name: Build RocksDB Windows
on:
  push:
    paths:
     - .github/workflows/build_rocksdb_win.yaml

jobs:
  build:
    runs-on: windows-latest        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build rocksdb
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DPORTABLE=1 -DROCKSDB_BUILD_SHARED=0 -DWITH_BENCHMARK_TOOLS=0 -DWITH_CORE_TOOLS=0 -DWITH_TOOLS=0 ..
          msbuild rocksdb.sln /m:2 /p:Configuration=Release
          ls Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: build/Release/rocksdb.lib
