name: Build
on: push

jobs:
  build_rocksdb:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Build rocksdb (Linux and macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          ./build_tools/build_detect_platform make_config.mk
          cat make_config.mk
          make static_lib -j2
          ls

      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v1.1

      - name: Build rocksdb (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
          cd ..
          msbuild build/rocksdb.sln /m:2
          ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb
          path: |
            librocks.a
            build/librocks.lib
