name: Build on MacOS
on:
  push:
    paths:
      - '!.github/workflows/*'
      - .github/workflows/build_macos.yaml
      - setup.py
      - src/*
      - tests/*

jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install RocksDB from Homebrew
        run: brew install rocksdb
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Build
        run: pip install . -v

      - name: Test
        run: pytest tests/

  pre-built:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Download RocksDB
        run: |
          gh release download rocksdb-8.0.0 -p '*macos_x86_64.tar.gz' -O rocksdb.tar.gz
          tar -xzvf rocksdb.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build
        run: pip install . -v
        env:
          CC: clang
          CXX: clang++

      - name: Test
        run: pytest tests/
