name: Build
on:
  push:
    paths-ignore:
      # - .github/workflows/build_rocksdb_*.yaml  # no point building Python bindings when new rocksdb lib is not built yet
      - README.md
      - .gitignore
      - .gitmodules

# jobs:
#   build:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           submodules: true

#       - name: Setup Python
#         uses: actions/setup-python@v3

#       - name: Download rocksdb library
#         run: |
#           python download_artifact.py --name=rocksdb_${{ runner.os }}
#           unzip artifact.zip
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Install dependencies
#         run: pip install pybind11 pytest

#       - name: Set env vars on macOS
#         if: runner.os == 'macOS'
#         run: |
#           echo CC=clang >> $GITHUB_ENV
#           echo CXX=clang++ >> $GITHUB_ENV
#           echo MACOSX_DEPLOYMENT_TARGET=10.13 >> $GITHUB_ENV
#           echo "ARCHFLAGS=-arch x86_64 -arch arm64" >> $GITHUB_ENV

#       - name: Build
#         run: python setup.py build_ext -i

#       - name: Test
#         run: python -m pytest tests/

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install RocksDB dependencies
        run: sudo apt-get -y install libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
      
      - name: Checkout RocksDB
        repository: facebook/rocksdb
        ref: v8.0.0
        path: rocksdb

      - name: Build RocksDB
        run: |
          cd rocksdb
          mkdir build
          cd build
          make -C .. static_lib -j

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Build
        run: pip install .

      - name: Test
        run: pytest .

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install RocksDB from Homebrew
        run: brew install rocksdb

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Build
        run: pip install .

      - name: Test
        run: pytest .
