name: Build RocksDB macOS
on:
  push:
    paths:
     - .github/workflows/build_rocksdb_mac.yaml

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Set env variables
        run: |
          echo CC=/usr/bin/clang >> $GITHUB_ENV
          echo CXX=/usr/bin/clang++ >> $GITHUB_ENV
          echo ARCHFLAG="-arch ${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build 3rd-party libs
        run: |
          echo $ARCHFLAG
          make rocksdbjavastatic_deps -j3
          ls -lh *.a

      - name: Build rocksdb
        run: |
          make static_lib -j3
          strip librocksdb.a
          cat make_config.mk
        env:
          PORTABLE: 1

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_${{ matrix.arch }}
          path: "*.a"

  create_universal:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download x86_64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_x86_64
          path: x86_64

      - name: Download arm64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_arm64
          path: arm64

      - name: Create universal build
        run: |
          for lib in $(ls x86_64/*.a)
          do
            filename=${lib##*/}
            echo "Creating universal lib for $filename"
            lipo -create -output $filename x86_64/$filename arm64/$filename
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: librocksdb.a
