name: Build RocksDB macOS
on:
  push:
    paths:
     - .github/workflows/build_rocksdb_mac.yaml

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Build rocksdb
        run: |
          make rocksdbjavastatic_deps -j3
          make static_lib -j3
          strip librocksdb.a
          cat make_config.mk
          ls -lh *.a
        env:
          PORTABLE: 1
          ARCHFLAG: -arch ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_${{ matrix.arch }}
          path: "*.a"

  create_universal:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download x86_64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_x86_64
          path: x86_64

      - name: Download arm64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_arm64
          path: arm64

      - name: Create universal build
        run: lipo -create -output librocksdb.a x86_64/librocksdb.a arm64/librocksdb.a

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: librocksdb.a
