name: Build
on:
  push:
    paths-ignore:
      - .github/workflows/build_rocksdb_*.yaml  # no point building Python bindings when new rocksdb lib is not built yet

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Download rocksdb library
        run: |
          python download_artifact.py --name=rocksdb_${{ runner.os }}
          unzip artifact.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: pip install pybind11 pytest

      - name: Use clang on macOS
        if: runner.os == 'macOS'
        run: |
          echo "CC=/usr/bin/clang" >> $GITHUB_ENV
          echo "CXX=/usr/bin/clang++" >> $GITHUB_ENV
          echo MACOSX_DEPLOYMENT_TARGET=10.9 >> $GITHUB_ENV

      - name: Build
        run: python setup.py build_ext -i

      - name: Test
        run: python -m pytest tests/
