name: Build RocksDB Linux
on:
  push:
    paths:
     - .github/workflows/build_rocksdb_linux.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build 3rd-party libs
        run: |
          cd rocksdb
          make rocksdbjavastatic_deps -j2
          ls -lh *.a

      - name: Build rocksdb
        run: |
          cd rocksdb
          make static_lib -j2
          strip --strip-debug librocksdb.a
          cat make_config.mk
        env:
          PORTABLE: 1
          CFLAGS: -fPIC
          CXXFLAGS: -fPIC
          EXTRA_CXXFLAGS: -I./bzip2-1.0.8 -I./lz4-1.9.3/lib -I./snappy-1.1.8 -I./snappy-1.1.8/build -I./zlib-1.2.12 -I./zstd-1.4.9/lib -I./zstd-1.4.9/lib/dictBuilder

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: "rocksdb/*.a"
