name: Build
on: push

jobs:
  build_rocksdb:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, arm64]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Build rocksdb
        run: |
          ./build_tools/build_detect_platform make_config.mk
          cat make_config.mk
          make static_lib -j2
          strip librocksdb.a
        env:
          ARCHFLAG: -arch ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_${{ matrix.arch }}
          path: librocksdb.a
          if-no-files-found: error

  build_rocksdb_windows:
    runs-on: windows-latest        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Add msbuild to PATH (Windows)
        uses: microsoft/setup-msbuild@v1.1

      - name: Build rocksdb
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
          msbuild rocksdb.sln /m:2 /p:Configuration=Release
          ls Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_x86_64
          path: build/Release/rocksdb.lib
          if-no-files-found: error
