name: Build
on: push

jobs:
  build_rocksdb_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Build rocksdb
        run: |
          make static_lib -j2
          strip librocksdb.a

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: librocksdb.a
          if-no-files-found: error

  build_rocksdb_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Build rocksdb
        run: |
          make static_lib -j2
          strip librocksdb.a
        env:
          ARCHFLAG: -arch ${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_${{ matrix.arch }}
          path: librocksdb.a
          if-no-files-found: error

  build_rocksdb_macos_universal:
    needs: build_rocksdb_macos
    runs-on: macos-latest
    steps:
      - name: Download x86_64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_x86_64
          path: x86_64

      - name: Download arm64 build
        uses: actions/download-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}_arm64
          path: arm64

      - name: Create universal build
        run: lipo -create -output librocksdb.a x86_64/librocksdb.a arm64/librocksdb.a

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: librocksdb.a
          if-no-files-found: error

  build_rocksdb_windows:
    runs-on: windows-latest        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: facebook/rocksdb

      - name: Add msbuild to PATH (Windows)
        uses: microsoft/setup-msbuild@v1.1

      - name: Build rocksdb
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release ..
          msbuild rocksdb.sln /m:2 /p:Configuration=Release
          ls Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rocksdb_${{ runner.os }}
          path: build/Release/rocksdb.lib
          if-no-files-found: error
