name: Build with conda
on:
  push:
    paths-ignore:
      - .github/workflows/build_linux.yaml
      - .github/workflows/build_macos_homebrew.yaml
      - .github/workflows/build_windows_vcpkg.yaml
      - .github/workflows/wheels.yaml
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    defaults:
      run:
        shell: bash -el {0}  # to make conda env work correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          channels: conda-forge

      - name: Install dependencies
        run: conda install -q -y rocksdb pytest

      - name: Setup for Windows
        if: runner.os == 'Windows'
        run: |
          conda install zlib
          echo LZ4_LIB=liblz4 >> $GITHUB_ENV
          echo BZ2_LIB=libbz2 >> $GITHUB_ENV

      - name: Build
        run: python -m pip install . -v

      - name: Test
        run: pytest tests/
