name: Build on MacOS with Homebrew
on:
  push:
    paths-ignore:
      - .github/workflows/build_conda.yaml
      - .github/workflows/build_linux.yaml
      - .github/workflows/build_windows_vcpkg.yaml
      - README.md
      - .gitignore

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install RocksDB from Homebrew
        run: brew install rocksdb
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Build
        run: pip install . -v

      - name: Test
        run: pytest tests/
